### ISSUE TITLE
Перенос на новый сервер

### ISSUE THREAD

**Issue by advocate441** [webjusticeru/frontend_kz#1]
194.4.56.118

**Comment by rdiff** [comment]
домен привязан?

**Comment by advocate441** [comment]
нет, я не умею

**Comment by advocate441** [comment]
Нужна твоя помощь, какие данные трбуются от нас?

**Comment by rdiff** [comment]
купить домен, у продавца или VPS привязать к ip
кто продавец? кто VPS?

**Comment by webjusticeru** [comment]
ip для домена webjustice.kz

**Comment by rdiff** [comment]
194.4.56.118
