### ISSUE TITLE
почта на домене KZ

### ISSUE THREAD

**Issue by webjusticeru** [webjusticeru/frontend_kz#2]
почта на домене KZ. info@webjustice.kz

задача в том чтобы для казахстана также работали уведомления и обратная связь, но через собственый емаил

привязанный таке к яндекс почта для домена

**Comment by rdiff** [comment]
:watch: **1**

**Comment by webjusticeru** [comment]
надеюсь это сюда:
![изображение](https://user-images.githubusercontent.com/43576326/56367421-e3eb9c80-61fd-11e9-9853-ef70bfaa3694.png)


`v=DKIM1; k=rsa; t=s; p=MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQC0or5HZMFe5/boaBYHANPy/kb5HANfnwc4qDrZ+c3s64pEr3EkNCC6D90Ixu4xxsbKf2dHZklrfyC3z4FftEbFrdUkJISTkdw03WnCFdGVWjxTnClC4nrwPCErZaTSa098kgAhKxlw07WgFb7E+gf28z3jQSkBuzK2aH5bUOWGGwIDAQAB`

**Comment by rdiff** [comment]
логин и пароль от почты нужен

**Comment by webjusticeru** [comment]
`v=DKIM1; k=rsa; t=s; p=MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQC0or5HZMFe5/boaBYHANPy/kb5HANfnwc4qDrZ+c3s64pEr3EkNCC6D90Ixu4xxsbKf2dHZklrfyC3z4FftEbFrdUkJISTkdw03WnCFdGVWjxTnClC4nrwPCErZaTSa098kgAhKxlw07WgFb7E+gf28z3jQSkBuzK2aH5bUOWGGwIDAQAB`

info@webjustice.kz
89FK#%

**Comment by rdiff** [comment]
info@webjustice.ru приватный ключ тоже кинь сюда

**Comment by rdiff** [comment]
хотя давай сначала с публичным протестим

**Comment by rdiff** [comment]
:watch: **2**
