### ISSUE TITLE
Тайтл на https://www.webjustice.kz/faq

### ISSUE THREAD

**Issue by webjusticeru** [webjusticeru/frontend_kz#4]
https://www.webjustice.kz/faq
тайтл проглядел, надо поправить на:

Вопросы-ответы по нотариальному заверению информации в интернет в Казахстане

**Comment by rdiff** [comment]
в факе ссылки ведут на ру

**Comment by webjusticeru** [comment]
ща проерю еще

**Comment by webjusticeru** [comment]
в каком вопросе, не вижу. вроде правил

**Comment by rdiff** [comment]
instagram

**Comment by webjusticeru** [comment]
у меня и у ильи постоянно исчезает панель редактора в факе
и и только в факе

**Comment by webjusticeru** [comment]
не могу даже ссылки поправить

**Comment by rdiff** [comment]
сейчас как?

**Comment by webjusticeru** [comment]
вот сейчас панель на месте
