### ISSUE TITLE
Вставить код

### ISSUE THREAD

**Issue by webjusticeru** [webjusticeru/frontend_kz#8]
Для подтверждения владения доменом для привязки почты к яндексу необходимо 
![изображение](https://user-images.githubusercontent.com/43576326/56355811-f1922980-61df-11e9-8b71-438176c05a53.png)

<meta name="yandex-verification" content="821e074cedea29ad" />

**Comment by rdiff** [comment]
может текстом

**Comment by webjusticeru** [comment]
фак
вставлял текст бля буду

**Comment by rdiff** [comment]
юзай на панеле <> для вставки кода

**Comment by webjusticeru** [comment]
[Новый текстовый документ.txt](https://github.com/webjusticeru/frontend_kz/files/3094026/default.txt)

**Comment by webjusticeru** [comment]
> 
> 
> юзай на панеле <> для вставки кода

хорошо

**Comment by rdiff** [comment]
:watch: **1**

**Comment by webjusticeru** [comment]
![изображение](https://user-images.githubusercontent.com/43576326/56356979-fb695c00-61e2-11e9-9e99-139eabf8ed10.png)
